version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"  # Required only for using Pi-hole as a DHCP server
      - "80:80/tcp" #pihole admin dashboard
    environment:
      TZ: "Asia/Kolkata" #add timezone here
      WEBPASSWORD: "manu7121998" #update your preferred password here
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    dns:
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped